// buzzer.c

#include "buzzer.h"

#include <avr/io.h>
#include <stdint.h>

// values used to write to the TCA0.SINGLE.PERBUF 
#define TONE1_PER 4934  // (PER+1)=4935 → ~337.87 Hz
#define TONE2_PER 5857  // (PER+1)=5858 → ~284.50 Hz
#define TONE3_PER 3691  // (PER+1)=3692 → ~451.20 Hz
#define TONE4_PER 9865  // (PER+1)=9866 → ~168.93 Hz

/** EX: 11.0.1

TASK: Implement the functions below to turn the buzzer ON and OFF.

The "buzzer_on" function should take a single argument, "tone_index",
which ranges from 0 to 3, and sets the frequency of the waveform output
generated by TCA0 correspondingly.

Ensure that the above macros reflect the four frequencies produced by
your program, given that TCA0 uses a DIV2 prescaler.
*/

void buzzer_on(const uint8_t tone_index)
{
    static const uint16_t base_periods[4] = {TONE1_PER, TONE2_PER, TONE3_PER, TONE4_PER};

    /** CODE: Write your code for Ex 11.0.1 within this function. */

    uint8_t idx = tone_index & 0x03;
    uint16_t per = base_periods[idx];

    // do nothing if period isnt set
    if (per == 0) {
        return;
    }

    // write duty first, then period, then duty again to avoid transient glitches
    uint16_t half = per >> 1;
    TCA0.SINGLE.CMP0BUF = half;      // pre-load duty
    TCA0.SINGLE.PERBUF = per;        // update period
    TCA0.SINGLE.CMP0BUF = half;      // ensure duty matches new period
}

void buzzer_off(void)
{
    /** CODE: Write your code for Ex 11.0.1 within this function. */

    // Set duty to 0% to silence the buzzer (keep TCA0 running)
    TCA0.SINGLE.CMP0BUF = 0;
}
